meta_product_name: "Typeless"
meta_title: "Typeless - A handy way of organizing your finances"
meta_description: "Typeless is an app that helps you organize your finances practically and easily by just uploading a photo from a receipt and 'Puff!' that's it."
meta_image: "logo.jpg"
