meta_product_name: "Typeless"
meta_title: "Typeless - A handy way of organizing your finances"
meta_description: "Typeless is an app that will help you organize your finances in a practical and easy way by just uploading a photo of your expense coupon and 'Puuf!' that's it"
meta_image: "logo.jpg"
