meta_product_name: "Typeless"
meta_title: "Typeless - A handy way of organizing your finances"
meta_description: "Typeless is a fantastic app that makes it easy and practical to organize your finances. All you have to do is take a photo of your receipt and upload it, and voila! It's that simple. "
meta_image: "logo.jpg"
